### PR TITLE
Wiki, role, notes and label modules.

### PR DESCRIPTION
**Pull request by carmen12**

### CODE REVIEW

**Comment by jlabusch** [comment]
@carmen12 would you mind fixing the indentation warnings before we merge please?

**Comment by carmen12** [comment]
@jlabusch I fixed the indentation issues.

**Comment by jlabusch** [comment]
We really should factor out a consistent fixer() that looks at username or email.
Going to merge anyway, that can come later.

**Comment by carmen12** [comment]
ok

**Pull request merged**
