### PR TITLE
Resource, Page and Chat Modules

### PR DESCRIPTION
**Pull request by carmen12**

### CODE REVIEW

**Comment by jlabusch** [comment]
@carmen12 can you take a look at some of the issues in CodeClimate?
Happy to discuss if you're not sure which ones are worth fixing.

**Comment by carmen12** [comment]
I'll try to fix as may as I can.

**Comment by carmen12** [comment]
So.. I'll fix them on my computer and then commit the changes and make a pull request again?

**Comment by jlabusch** [comment]
Yep, but you should be able to add more commits to this PR rather than making a new one.

**Comment by carmen12** [comment]
ok

**Comment by jlabusch** [comment]
Closing as discussed.

**Pull request closed without merging**
